<a href="https://colab.research.google.com/github/Saifullah785/Deep_Learning_using_PyTorch/blob/main/Lecture_06_Dataset_%26_DataLoader_Class_in_PyTorch/Lecture_06_Pytorch_Training_Pipeline_Using_Dataset_and_Dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
# Load the dataset into a pandas DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
# Display the shape of the DataFrame
df.shape

(569, 33)

In [4]:
# Drop unnecessary columns from the DataFrame
df.drop(columns=['id','Unnamed: 32'], inplace= True)

In [5]:
# Display the first few rows of the updated DataFrame
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train test split

In [6]:
# Perform train-test split on the dataset
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
# Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [8]:
# Display the scaled training features
X_train

array([[ 0.86971069, -0.64327187,  1.00987588, ...,  2.16881093,
         1.82584008,  1.24493634],
       [-0.70662157, -1.19440929, -0.7589562 , ..., -0.47774689,
         0.31560571, -0.95103155],
       [-0.03522079, -0.74053142, -0.10072702, ..., -0.60646094,
        -0.27283795, -0.64375362],
       ...,
       [-0.11403741,  0.72067744, -0.0647235 , ...,  0.82015828,
         0.2827405 ,  0.53752177],
       [ 1.83302484,  0.60257657,  1.76383209, ...,  0.9616361 ,
        -0.45437907, -0.92458089],
       [-0.03230166,  1.8461093 , -0.03295568, ..., -0.14096818,
        -1.01621756, -0.03201167]])

In [9]:
# Display the training labels
y_train

25     M
281    B
437    B
370    M
357    B
      ..
20     B
542    B
196    M
365    M
560    B
Name: diagnosis, Length: 455, dtype: object

**Label Encoding**

In [10]:
# Perform label encoding on the target variable
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
# Display the encoded training labels
y_train

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,

**Numpy arrays to Pytorch tensors**

In [12]:
# Convert numpy arrays to PyTorch tensors
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [13]:
# Display the shape of the training features tensor
X_train.shape

torch.Size([455, 30])

In [14]:
# Display the shape of the training labels tensor
y_train.shape

torch.Size([455])

In [15]:
# Define a custom PyTorch Dataset class
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [16]:
# Create instances of the custom dataset for training and testing
train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

In [17]:
# Access an example item from the training dataset
train_dataset[10]

(tensor([ 1.7513,  0.1116,  1.6495,  1.8174, -1.1188, -0.3406,  0.3700,  0.7510,
          0.4314, -1.6776,  0.6799, -0.9318,  0.5005,  0.8214, -0.8366, -0.6468,
         -0.1614,  0.1123,  0.1656, -0.8191,  1.4428, -0.3960,  1.3136,  1.4238,
         -1.1510, -0.6340, -0.0248,  0.4388,  0.2436, -1.3759]),
 tensor(1.))

In [18]:
# Create DataLoader instances for training and testing
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

**Defining the Model**

In [19]:
# Define the neural network model
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

# Important Parameters

In [20]:
# Define important training parameters
learning_rate = 0.1
epochs = 25

In [21]:
# Initialize the model, optimizer, and loss function
model = MySimpleNN(X_train.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

loss_funcion = nn.BCELoss()

#**Training Pipeline**

In [22]:
# Training loop for the neural network
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    y_pred = model(batch_features)

    loss = loss_funcion(y_pred, batch_labels.view(-1, 1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

  print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 0, Loss: 0.21100139617919922
Epoch: 1, Loss: 0.11340324580669403
Epoch: 2, Loss: 0.07820575684309006
Epoch: 3, Loss: 0.061756495386362076
Epoch: 4, Loss: 0.11945556104183197
Epoch: 5, Loss: 0.06865747272968292
Epoch: 6, Loss: 0.08947128057479858
Epoch: 7, Loss: 0.2979920208454132
Epoch: 8, Loss: 0.0937059074640274
Epoch: 9, Loss: 0.05787987634539604
Epoch: 10, Loss: 0.016376934945583344
Epoch: 11, Loss: 0.009587789885699749
Epoch: 12, Loss: 0.14472118020057678
Epoch: 13, Loss: 0.036984581500291824
Epoch: 14, Loss: 0.09283055365085602
Epoch: 15, Loss: 0.06543238461017609
Epoch: 16, Loss: 0.03371637687087059
Epoch: 17, Loss: 0.023352626711130142
Epoch: 18, Loss: 0.03891703486442566
Epoch: 19, Loss: 0.004012014251202345
Epoch: 20, Loss: 0.0036016458179801702
Epoch: 21, Loss: 0.0823790654540062
Epoch: 22, Loss: 0.02808929607272148
Epoch: 23, Loss: 0.05601104721426964
Epoch: 24, Loss: 0.004038841929286718


# Evaluation

In [23]:
# Evaluate the trained model's accuracy
model.eval()

# set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    # forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    # calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(f'Overall Accuracy: {overall_accuracy:.4f}')

Overall Accuracy: 0.9861
