<a href="https://colab.research.google.com/github/Saifullah785/Deep_Learning_using_PyTorch/blob/main/Lecture_02_Tensors_in_Pytorch/Lecture_02_Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the torch library and print its version.
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
# Check if a GPU is available and print device information, otherwise indicate CPU usage.
if torch.cuda.is_available():
  print('GPU is available')
  print(f'using GPU: {torch.cuda.get_device_name(0)}')
else:
  print('GPU is not available. Using CPU.')

GPU is not available. Using CPU.


# Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[1.5655e+08, 4.5289e-41, 1.5655e+08],
        [4.5289e-41, 1.4574e-43, 6.4460e-44]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
c = torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2964, 0.2394, 0.0194],
        [0.6858, 0.0482, 0.3628]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.3797, 0.6053, 0.1346],
        [0.6173, 0.3297, 0.3396]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Set a manual seed for reproducibility and generate a random tensor.
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange

print('using arange ->', torch.arange(0,10,2))

# linspace

print('using linspace ->', torch.linspace(0,10,10))

# using eye
print('using eye ->', torch.eye(5))

# using full
print('using full ->', torch.full((2,3), 5))



using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
# Define a 2x3 tensor named x.
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Get the shape of tensor x.
x.shape

torch.Size([2, 3])

In [ ]:
# Create an empty tensor with the same shape as x.
torch.empty_like(x)

tensor([[      922695264, 135465083505152,               1],
        [              6,               0,               0]])

In [ ]:
# Create a tensor of zeros with the same shape as x.
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# Create a tensor of ones with the same shape as x.
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Create a random tensor with the same shape as x and float32 data type.
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5584, 0.4276, 0.4801],
        [0.7585, 0.1862, 0.4210]])

# Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# Create a tensor with float64 data type.
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to ()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

---

# 1.Scalar operation

In [ ]:
# Create a random 2x2 tensor named x for scalar operations.
x = torch.rand(2,2)
x

tensor([[0.0120, 0.9670],
        [0.0355, 0.5636]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
((x * 100)//3)% 2
# power
x **2

tensor([[1.4486e-04, 9.3508e-01],
        [1.2573e-03, 3.1760e-01]])

2.Element wise operation

In [ ]:
# Define two random 2x3 tensors, a and b, for element-wise operations.
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.3328, 0.4101, 0.1917],
        [0.1752, 0.4050, 0.2534]])
tensor([[0.8355, 0.8035, 0.4658],
        [0.9385, 0.0181, 0.7852]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3328, 0.4101, 0.1917],
        [0.1752, 0.0059, 0.2534]])

In [ ]:
# Define a tensor named c for absolute and negation operations.
c = torch.tensor([1,-2, 3, -4])

In [ ]:
# Display tensor c.
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# Define a tensor named d for rounding operations.
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# Apply the floor operation to tensor d.
torch.floor(d)

In [ ]:
# clamp
torch.clamp(d, min=2, max= 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
# Create a random integer tensor named e for reduction operations.
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [6., 9., 3.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15., 18.])

In [ ]:
# mean
torch.mean(e)
# torch along col
torch.mean(e, dim=0)
# torch along row
torch.mean(e, dim=1)

tensor([5., 6.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
# product
torch.prod(e)

tensor(17010.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.3452)

In [ ]:
# variance
torch.var(e)

tensor(5.5000)

In [ ]:
# argmax
torch.argmax(e)

tensor(4)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

# 4.Matrix Operations

In [ ]:
# Define two random integer tensors, f and g, for matrix operations.
f = torch.randint(size=(2,3), low=0, high=10)

g = torch.randint(size=(3,2), low=0, high=10)

print(f)

print(g)

tensor([[7, 2, 9],
        [7, 4, 6]])
tensor([[6, 0],
        [9, 4],
        [5, 1]])


In [ ]:
# matrix multiplication

torch.matmul(f, g)

tensor([[105,  17],
        [108,  22]])

In [ ]:
# Define two vectors for dot product calculation.
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product

torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose

torch.transpose(f, 0, 1)

tensor([[7, 7],
        [2, 4],
        [9, 6]])

In [ ]:
# Define a random 3x3 tensor named h for determinant and inverse calculations.
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 7., 4.],
        [4., 3., 9.],
        [6., 5., 7.]])

In [ ]:
# determintant

torch.det(h)

tensor(142.0000)

In [ ]:
# inverse

torch.inverse(h)

tensor([[-0.1690, -0.2042,  0.3592],
        [ 0.1831, -0.0704, -0.0141],
        [ 0.0141,  0.2254, -0.1549]])

# Comparison operations

In [ ]:
# Define two random integer tensors, i and j, for comparison operations.
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 2, 4],
        [0, 1, 4]])
tensor([[4, 4, 5],
        [1, 2, 7]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to


tensor([[True, True, True],
        [True, True, True]])

#6.Special functions

In [ ]:
# Define a random tensor named k for special mathematical functions.
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 9., 7.],
        [9., 1., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 2.1972, 1.9459],
        [2.1972, 0.0000, 0.6931]])

In [ ]:
#exp
torch.exp(k)

tensor([[1.4841e+02, 8.1031e+03, 1.0966e+03],
        [8.1031e+03, 2.7183e+00, 7.3891e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 3.0000, 2.6458],
        [3.0000, 1.0000, 1.4142]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9999, 0.9991],
        [0.9999, 0.7311, 0.8808]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[1.7986e-02, 9.9966e-01, 9.9331e-01],
        [9.8201e-01, 3.3535e-04, 6.6929e-03]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 9., 7.],
        [9., 1., 2.]])

# inplace Operations

In [ ]:
# Define two random tensors, m and n, for in-place operations.
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5494, 0.9703, 0.9432],
        [0.5122, 0.7257, 0.9392]])
tensor([[0.1715, 0.4207, 0.5786],
        [0.6887, 0.0508, 0.4627]])


In [ ]:
# Perform in-place addition of tensor n to tensor m.
m.add_(n)

tensor([[0.7209, 1.3910, 1.5218],
        [1.2009, 0.7765, 1.4019]])

In [ ]:
# Display tensor m after the in-place addition.
m

tensor([[0.7209, 1.3910, 1.5218],
        [1.2009, 0.7765, 1.4019]])

In [ ]:
# Display tensor n.
n

tensor([[0.1715, 0.4207, 0.5786],
        [0.6887, 0.0508, 0.4627]])

In [ ]:
# Apply the ReLU activation function to tensor m.
torch.relu(m)

tensor([[0.7209, 1.3910, 1.5218],
        [1.2009, 0.7765, 1.4019]])

In [ ]:
# Perform the ReLU activation function in-place on tensor m.
m.relu_()

tensor([[0.7209, 1.3910, 1.5218],
        [1.2009, 0.7765, 1.4019]])

In [ ]:
# Display tensor m after the in-place ReLU operation.
m

tensor([[0.7209, 1.3910, 1.5218],
        [1.2009, 0.7765, 1.4019]])

# Copying a Tensor

In [ ]:
# Define a random tensor named a.
a = torch.rand(2,3)
a

tensor([[0.9233, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Assign tensor a to tensor b, creating a view (both refer to the same memory).
b = a

In [ ]:
# Display tensor b.
b

tensor([[0.9233, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Modify an element in tensor a.
a[0][0] = 0

In [ ]:
# Display tensor a after modification.
a

tensor([[0.0000, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Display tensor b, which will reflect the changes made to a as it's a view.
b

tensor([[0.0000, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Get the memory address (id) of tensor a.
id(a)

134081034736160

In [ ]:
# Get the memory address (id) of tensor b.
id(b)

134081034736160

In [ ]:
# Create a deep copy of tensor a to tensor b, ensuring independent memory.
b = a.clone()

In [ ]:
# Display tensor a.
a

tensor([[0.0000, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Display tensor b.
b

tensor([[0.0000, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Modify an element in tensor a.
a[0][0] = 10

In [ ]:
# Display tensor a after modification.
a

tensor([[10.0000,  0.6302,  0.5970],
        [ 0.5199,  0.0198,  0.3999]])

In [ ]:
# Display tensor b, which should not reflect changes in a because it is a clone.
b

tensor([[0.0000, 0.6302, 0.5970],
        [0.5199, 0.0198, 0.3999]])

In [ ]:
# Get the memory address (id) of tensor a.
id(a)

134081034736160

In [ ]:
# Get the memory address (id) of tensor b.
id(b)

134081034742400