<a href="https://colab.research.google.com/github/Saifullah785/Deep_Learning_using_PyTorch/blob/main/Lecture_02_Tensors_in_Pytorch/Lecture_02_Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)


2.9.0+cu126


In [2]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'using GPU: {torch.cuda.get_device_name(0)}')
else:
  print('GPU is not available. Using CPU.')

GPU is not available. Using CPU.


# Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[1.5655e+08, 4.5289e-41, 1.5655e+08],
        [4.5289e-41, 1.4574e-43, 6.4460e-44]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# using ones
c = torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# using rand
torch.rand(2,3)

tensor([[0.2964, 0.2394, 0.0194],
        [0.6858, 0.0482, 0.3628]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.3797, 0.6053, 0.1346],
        [0.6173, 0.3297, 0.3396]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange

print('using arange ->', torch.arange(0,10,2))

# linspace

print('using linspace ->', torch.linspace(0,10,10))

# using eye
print('using eye ->', torch.eye(5))

# using full
print('using full ->', torch.full((2,3), 5))



using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])
