<a href="https://colab.research.google.com/github/Saifullah785/Deep_Learning_using_PyTorch/blob/main/Lecture_04_Pytorch_Training_Pipeline/Lecture_04_Pytorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
# Display the first few rows of the DataFrame
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
# Display the shape of the DataFrame
df.shape

(569, 33)

In [5]:
# Drop unnecessary columns
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
# Display the DataFrame after dropping columns
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# train test split

In [7]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

#Scaling

In [8]:
# Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
#

In [9]:
# Display the scaled training features
X_train

array([[-0.68284778, -0.22209668, -0.66932225, ...,  0.09526438,
        -0.16093233,  0.3438262 ],
       [-0.5392983 , -0.29200766, -0.54460627, ..., -0.87141696,
        -0.80420924, -0.38276842],
       [-0.48960809,  0.68441567, -0.48224829, ..., -0.49844777,
        -1.02613977,  0.33585915],
       ...,
       [-0.45372072, -0.45979401, -0.45826444, ..., -0.15050207,
         0.2073437 , -0.4188857 ],
       [-0.23287536, -0.52737462, -0.29437486, ..., -0.27740692,
        -0.64339001, -0.43906888],
       [-0.34329804, -0.71613426, -0.38111642, ..., -0.85801152,
         1.1224051 , -0.73703641]])

In [10]:
# Display the training labels
y_train

106    B
480    B
163    B
139    B
214    M
      ..
434    B
456    B
497    B
224    B
268    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [11]:
# Encode target labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [12]:
# Display the encoded training labels
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,

# Numpy arrays to Pytorch tensors

In [13]:
# Convert numpy arrays to PyTorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
# Display the shape of the training features tensor
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
# Display the shape of the training labels tensor
y_train_tensor.shape

torch.Size([455])

#**Defining the model**

In [16]:
# Define a simple neural network class
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64,
    requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [17]:
# Define important training parameters
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# Training pipeline for the neural network
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):

  y_pred = model.forward(X_train_tensor)

  loss = model.loss_function(y_pred, y_train_tensor)

  loss.backward()

  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.025001060939828
Epoch: 2, Loss: 2.878128460062771
Epoch: 3, Loss: 2.7256245041389704
Epoch: 4, Loss: 2.572899704275481
Epoch: 5, Loss: 2.4143100869883
Epoch: 6, Loss: 2.2529995322960885
Epoch: 7, Loss: 2.0953645542379116
Epoch: 8, Loss: 1.9444863527450922
Epoch: 9, Loss: 1.7978359345411823
Epoch: 10, Loss: 1.655056322358546
Epoch: 11, Loss: 1.5188216424265957
Epoch: 12, Loss: 1.393679858649187
Epoch: 13, Loss: 1.2798686967202437
Epoch: 14, Loss: 1.1810845101933354
Epoch: 15, Loss: 1.097791697127072
Epoch: 16, Loss: 1.0296936409967798
Epoch: 17, Loss: 0.9755721435609689
Epoch: 18, Loss: 0.9334008704268858
Epoch: 19, Loss: 0.9007400525925777
Epoch: 20, Loss: 0.8752077880337767
Epoch: 21, Loss: 0.8548056250527056
Epoch: 22, Loss: 0.83802812799798
Epoch: 23, Loss: 0.8238202281859354
Epoch: 24, Loss: 0.8114749565486181
Epoch: 25, Loss: 0.8005302283545528


In [19]:
# Display the trained model's bias
model.bias

tensor([-0.1629], dtype=torch.float64, requires_grad=True)

# Evaluation

In [20]:
# Evaluate the model's accuracy on the test set

with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6184980273246765
